### ISSUE TITLE
QR code reading error on android devices

### ISSUE THREAD

**Issue by takusng** [Tiqr/tiqr-app-android#43]
Recently, when I try to read a QR code using the tiqr app on my android device, I get an error.
The error message is as follows.

The app was opened from an invalid URL.
The link which was used to open the appdoes not have a valid format. No action will be taken.

I think it is a problem with the android version of the tiqr app, as it reads fine in the iphone tiqr app.

I would appreciate it if you could tell me how to respond.

**Comment by phavekes** [comment]
Where are you trying to authenticate to?

**Comment by takusng** [comment]
I have a tiqr server set up on my university's authentication server.

I used the following site as a reference for my setup.
https://meatwiki.nii.ac.jp/confluence/display/tiqr/Installing+Shibbolized+Tiqr

I have been able to enroll and authenticate without any problems, but recently I have been getting errors when reading QR codes.

It is not only me, but many of our university's users are experiencing the error.

**Comment by phavekes** [comment]
In the latest version of the app, the domainnames that are allowed so start authentication are limited.

https://github.com/Tiqr/tiqr-app-android/blob/492e36f7afde79cdcf8190b0a046caa0e9740117/app/build.gradle.kts#L51

**Comment by takusng** [comment]
Does this mean that once the University's domain is added to the configuration, the error will no longer occur?

**Comment by takusng** [comment]
Thank you very much.
Our domain name is "ku-sso.cis.kanazawa-u.ac.jp".

**Comment by phavekes** [comment]
For IOS: https://github.com/Tiqr/tiqr-app-ios/pull/31

**Comment by phavekes** [comment]
Please join the test-track on Google Play to test authentication and enrollment before the new version is released:

https://play.google.com/apps/testing/org.tiqr.authenticator

**Comment by esearrose** [comment]
We are a French organization working for public benefit in the HealthCare sector and have been using Tiqr successfully until now for authentication on our servers. However, since Tiqr 4.x, connections on our servers (domains : securite-test.sante-na.fr, securite.sante-na.fr) do not work anymore.

Could you please add sante-na.fr to the allowed domains in the next release ?

Thanx

**Comment by phavekes** [comment]
The updated app is in the Google Play open test now. Could you test if it works for you?

**Comment by esearrose** [comment]
It works perfectly. Many thanks !

**Comment by pmeulen** [comment]
This is not a scalable way to do this for Tiqr IMO. Suddenly blocking new registrations is not a nice way to find out about this for existing users of the Tiqr app.

We should roll back this change.

**Comment by phavekes** [comment]
https://github.com/Tiqr/tiqr-app-android/pull/46

**Comment by phavekes** [comment]
A version of the Android-Tiqr app (4.0.13) allowing all domain-names is available for internal testers, and will soon be moved to production.
